version: "3.8"
services:
  express-api:
    build: ./api
    container_name: express-api
    ports:
      - "3242:3242"
    environment:
      - NODE_ENV=development
    depends_on:
      - loki
      - tempo
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
  tempo:
    image: grafana/tempo:2.7.2
    container_name: tempo
    ports:
      - "3200:3200" # HTTP API port
      - "4318:4318" # OTLP HTTP receiver port
      - "9095:9095" # gRPC port
    command: ["-config.file=/etc/tempo/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo/tempo.yaml
      - tempo-data:/var/tempo

  # promtail:
  #   image: grafana/promtail:latest
  #   container_name: promtail
  #   volumes:
  #     - /var/log:/var/log
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /var/lib/docker/containers:/var/lib/docker/containers:ro
  #     - ./promtail.yaml:/etc/promtail/promtail.yaml
  #   command: -config.file=/etc/promtail/promtail.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3006:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./gf-datasources.yaml:/etc/grafana/provisioning/datasources/gf-datasources.yaml
volumes:
  grafana-storage:
  tempo-data:
